### ISSUE TITLE
Missing ol.tilegrid.XYZ in OpenLayers 3.7

### ISSUE THREAD

**Issue by gejgalis** [openlayers/ol3-cesium#214] opened 2015-07-31 13:12 UTC
OpenLayers: `3.7`
ol3-cesium: `1.6`
Cesium: `1.11`

`ol.tilegrid.XYZ` has been changed to `ol.tilegrid.createXYZ()` in OpenLayers 3.6

**Comment by gberaudo** [comment] 2015-08-03 13:36
Duplicate of https://github.com/openlayers/ol3-cesium/pull/201 which is underwork.

**Closed by gberaudo** 2015-08-03 13:36 UTC
